Cameras:
  # Manufacturer
  Andor:
    # Type
    iXon Ultra:
      # Model
      DU897_BV:
        # Serial number
        9603:       # Miblab
          Baseline: 100
          Sensitivity:
            # EM gain
            true:
              # Sensitivity for each readout rate, for each preamp gain (1, 2, 3)
              17.000 MHz: [15.7, 9.3, 5.26]
              10.000 MHz: [16.2, 8.41, 5.08]
              5.000 MHz: [18.3, 8.7, 4.56]
              1.000 MHz: [18.3, 8.66, 4.60]
            false:
              3.000 MHz: [4.0, 3.13, 1.47]
              1.000 MHz: [4.01, 3.1, 1.45]
              0.080 MHz: [4.05, 3.12, 1.45]
          Quantum Efficiency:
            # Excitation wavelength
            489: 0.95
            561: 0.96
            640: 0.9
        9418:       # Loaner. SENSITIVITIES SHOULD BE UPDATED! These are simply copied from the Miblab camera
          Baseline: 100
          Sensitivity:
            # EM gain
            true:
              # Sensitivity for each readout rate, for each preamp gain (1, 2, 3)
              17.000 MHz: [15.7, 9.3, 5.26]
              10.000 MHz: [16.2, 8.41, 5.08]
              5.000 MHz: [18.3, 8.7, 4.56]
              1.000 MHz: [18.3, 8.66, 4.60]
            false:
              3.000 MHz: [4.0, 3.13, 1.47]
              1.000 MHz: [4.01, 3.1, 1.45]
              0.080 MHz: [4.05, 3.12, 1.45]
          Quantum Efficiency:
            # Excitation wavelength
            489: 0.95
            561: 0.96
            640: 0.9
    # Type
    iXon:
      # Model
      DU897_BV:
        # Serial number
        9252:       # Boston. SENSITIVITIES SHOULD BE UPDATED! These are simply copied from the Miblab camera
          Baseline: 100
          Sensitivity:
            # EM gain
            true:
              # Sensitivity for each readout rate, for each preamp gain (1, 2, 3)
              17.000 MHz: [15.7, 9.3, 5.26]
              10.000 MHz: [16.2, 8.41, 5.08]
              5.000 MHz: [18.3, 8.7, 4.56]
              1.000 MHz: [18.3, 8.66, 4.60]
            false:
              3.000 MHz: [4.0, 3.13, 1.47]
              1.000 MHz: [4.01, 3.1, 1.45]
              0.080 MHz: [4.05, 3.12, 1.45]
          Quantum Efficiency:
            # Excitation wavelength
            489: 0.95
            561: 0.96
            640: 0.9
