Cameras:
  Andor iXon X-9603:   # Miblab
    Sensor: EMCCD
    Quantum Efficiency:
      # Excitation wavelength
      489: 0.95
      561: 0.96
      640: 0.9
    Sensitivity:
      # EM gain
      true:
        # Sensitivity for each readout rate, for each preamp gain (1, 2, 3)
        17.000 MHz: [15.9, 9.34, 5.32]
        10.000 MHz: [16.5, 8.4, 5.12]
        5.000 MHz: [18.1, 8.74, 4.63]
        1.000 MHz: [18.3, 8.86, 4.58]
      false:
        3.000 MHz: [4.03, 3.14, 1.47]
        1.000 MHz: [4.09, 3.09, 1.47]
        0.080 MHz: [4.04, 3.09, 1.44]
  Andor iXon X-9418:   # Loaner. The calibration numbers are the ones from the original Miblab camera.
    Sensor: EMCCD
    Quantum Efficiency:
      # Excitation wavelength
      489: 0.95
      561: 0.96
      640: 0.9
    Sensitivity:
      # EM gain
      true:
        # Sensitivity for each readout rate, for each preamp gain (1, 2, 3)
        17.000 MHz: [15.7, 9.3, 5.26]
        10.000 MHz: [16.2, 8.41, 5.08]
        5.000 MHz: [18.3, 8.7, 4.56]
        1.000 MHz: [18.3, 8.66, 4.60]
      false:
        3.000 MHz: [4.0, 3.13, 1.47]
        1.000 MHz: [4.01, 3.1, 1.45]
        0.080 MHz: [4.05, 3.12, 1.45]
  Andor Zyla VSC-01223:     # Generic Zyla
    Sensor: sCMOS
    Quantum Efficiency:
      489: 1
      561: 1
      640: 1
