Cameras:
  Andor iXon X-9603:
    Sensor: EMCCD
    Baseline: 200
    Quantum Efficiency:
      # Emission wavelength
      525: 0.95
      595: 0.96
      700: 0.9
    Sensitivity:
      # EM gain
      true:
        # Readout rate
        17.000 MHz:
          # For automated gain setting, the names should be the same as given by MicroManager metadata.
          Gain 1: 15.9
          Gain 2: 9.34
          Gain 3: 5.32
        10.000 MHz:
          Gain 1: 16.5
          Gain 2: 8.4
          Gain 3: 5.12
        5.000 MHz:
          Gain 1: 18.1
          Gain 2: 8.74
          Gain 3: 4.63
        1.000 MHz:
          Gain 1: 18.3
          Gain 2: 8.86
          Gain 3: 4.58
      false:
        3.000 MHz:
          Gain 1: 4.03
          Gain 2: 3.14
          Gain 3: 1.47
        1.000 MHz:
          Gain 1: 4.09
          Gain 2: 3.09
          Gain 3: 1.47
        0.080 MHz:
          Gain 1: 4.04
          Gain 2: 3.09
          Gain 3: 1.44
    Channel Device:
      # This information is used to automatically set the emission wavelength based on MicroManager metadata
      Name: TIFilterBlock1-Label
      Emission Wavelengths:
        1-R640: 700
        2-G561: 595
        3-B489: 525
  Andor Zyla VSC-01223:
    Sensor: sCMOS
    Baseline: 100
    Quantum Efficiency:
      525: 0.7
      595: 0.72
      700: 0.64
    Sensitivity:
      540 MHz:
        12-bit (high well capacity): 7.18
        12-bit (low noise): 0.29
        16-bit (low noise & high well capacity): 0.46
      200 MHz:
        12-bit (high well capacity): 7.0
        12-bit (low noise): 0.26
        16-bit (low noise & high well capacity): 0.45
    Channel Device:
      # This information is used to automatically set the emission wavelength based on MicroManager metadata
      Name: TIFilterBlock1-Label
      Emission Wavelengths:
        1-R640: 700
        2-G561: 595
        3-B489: 525
  Simulation:
    Sensor: Simulation
